{% set name = "lava" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lava-nc/lava/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a16a9c64d48e9e4438801acb41b058a8fb8855b7b620c01b0eba5123c8247388
  patches:
    - fix-setup-py.patch

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    # only required to get the version from build.py
    - pybuilder
  run:
    - python >=3.6
    - matplotlib-base
    - numpy

test:
  imports:
    - lava
    - lava.magma
    - lava.proc
  commands:
    - python -m unittest

about:
  home: https://github.com/lava-nc/lava
  summary: Lava is an open-source software framework for developing neuro-inspired applications and mapping them to neuromorphic hardware.
  license: BSD-3-Clause AND LGPL-2.1-or-later
  license_file:
    - LICENSE
    - src/lava/magma/core/LICENSE
    - src/lava/magma/compiler/LICENSE
    - src/lava/magma/runtime/LICENSE
    - src/lava/proc/LICENSE
    - src/lava/utils/LICENSE
    - tutorials/LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
