{% set name = "lava" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lava-nc/lava/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 817230a69b9acc26f33f0adba211a80747204d4a9705a5db3f5c6e93c8f77589

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.11
    - poetry-core
  run:
    - python >=3.6,<3.11
    - matplotlib-base
    - numpy
    - scipy
    - networkx

test:
  requires:
    - pytest
    - nbformat
  source_files:
    - tests
  imports:
    - lava
    - lava.magma
    - lava.proc
  # commands:
  #   - pytest

about:
  home: https://github.com/lava-nc/lava
  summary: Lava is an open-source software framework for developing neuro-inspired applications and mapping them to neuromorphic hardware.
  license: BSD-3-Clause AND LGPL-2.1-or-later
  license_file:
    - LICENSE
    - src/lava/magma/core/LICENSE
    - src/lava/magma/compiler/LICENSE
    - src/lava/magma/runtime/LICENSE
    - src/lava/proc/LICENSE
    - src/lava/utils/LICENSE
    - tutorials/LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - mgkwill
