{% set name = "lava" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lava-nc/lava/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 54c42de3e13b66baf3692e955d6363d814e5409b5c68c1284d961e7680965588

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry-core
  run:
    - python >=3.6
    - matplotlib-base
    - numpy
    - scipy

test:
  requires:
    - pytest
    - nbformat
  source_files:
    - tests
  imports:
    - lava
    - lava.magma
    - lava.proc
  commands:
    - pytest

about:
  home: https://github.com/lava-nc/lava
  summary: Lava is an open-source software framework for developing neuro-inspired applications and mapping them to neuromorphic hardware.
  license: BSD-3-Clause AND LGPL-2.1-or-later
  license_file:
    - LICENSE
    - src/lava/magma/core/LICENSE
    - src/lava/magma/compiler/LICENSE
    - src/lava/magma/runtime/LICENSE
    - src/lava/proc/LICENSE
    - src/lava/utils/LICENSE
    - tutorials/LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
