{% set name = "lava" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lava-nc/lava/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d418de7401fc9ee34bd8c016b63ff9cefddcbea7211879c2f63418fb755e3659

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core
  run:
    - python >={{ python_min }},<3.11
    - matplotlib-base
    - numpy
    - scipy
    - networkx

test:
  requires:
    - pytest
    - nbformat
    - python {{ python_min }}
  source_files:
    - tests
  imports:
    - lava
    - lava.magma
    - lava.proc
  # commands:
  #   - pytest

about:
  home: https://github.com/lava-nc/lava
  summary: Lava is an open-source software framework for developing neuro-inspired applications and mapping them to neuromorphic hardware.
  license: BSD-3-Clause AND LGPL-2.1-or-later
  license_file:
    - LICENSE
    - src/lava/magma/core/LICENSE
    - src/lava/magma/compiler/LICENSE
    - src/lava/magma/runtime/LICENSE
    - src/lava/proc/LICENSE
    - src/lava/utils/LICENSE
    - tutorials/LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - mgkwill
